# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7cb821f0597e239a5bb51dbad0ecbab8a7cf8dce51f6b29afe6a4b3a8e3b598e43adab6804fc17a04bd874675e5ac6f8640121272e26dfa4ef9bfe7a3266048

test:
  secret_key_base: bc3cc6ce7b13be0982c1f387de34d01c5f1f503983b71df2b551c34ad3f32262a42a0a7c558769abdd3c08a575779a973f1871218043947ee7e68d00b056a3b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
